-- Parser sources: 10 top sites + 8 SEO satellites (18 total, work-permit-poland.com overlap = 17 unique)
INSERT IGNORE INTO job_parser_sources (name, domain, parse_url, parse_type, category, selectors) VALUES
-- === TOP 10 sites (best in Poland per trade unions) ===
('Biuro Imigracyjne', 'biuro-imigracyjne.com', 'https://biuro-imigracyjne.com', 'html_list', 'immigration', '{"job_list":"article, .job-list, .vacancy-list, .offers","title":"h2, h3, .title","link":"a[href]","city":".city, .location","salary":".salary, .price"}'),
('EuroVisaNews', 'eurovisanews.com', 'https://eurovisanews.com', 'html_list', 'visa_news', '{"job_list":"article, .post-list, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Karta Pobytu Net', 'karta-pobytu.net', 'https://karta-pobytu.net', 'html_list', 'residence_permit', '{"job_list":"article, .job-list, .post","title":"h2, h3, .title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Karta Pobytu 24', 'kartapobytu24.com', 'https://kartapobytu24.com', 'html_list', 'residence_permit', '{"job_list":"article, .offers, .vacancy","title":"h2, h3, .title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Legalizacja Polska COM', 'legalizacja-polska.com', 'https://legalizacja-polska.com', 'html_list', 'legalization', '{"job_list":"article, .job-list, .post","title":"h2, h3, .title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('PESEL Online', 'pesel-online.com', 'https://pesel-online.com', 'html_list', 'documents', '{"job_list":"article, .services, .post","title":"h2, h3, .title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Pobyt Stalowy', 'pobyt-stalowy.com', 'https://pobyt-stalowy.com', 'html_list', 'permanent_residence', '{"job_list":"article, .offers, .vacancy","title":"h2, h3, .title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Poland Pulse', 'polandpulse.com', 'https://polandpulse.com', 'html_list', 'news_jobs', '{"job_list":"article, .post-list, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Warsaw Daily', 'warsawdaily.org', 'https://warsawdaily.org', 'html_list', 'news_jobs', '{"job_list":"article, .post-list, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Work Permit Poland', 'work-permit-poland.com', 'https://work-permit-poland.com', 'html_list', 'work_permit', '{"job_list":"article, .job-list, .post","title":"h2, h3, .title","link":"a[href]","city":".city, .location","salary":".salary"}'),
-- === 8 SEO Satellites (WinCase own sites) ===
('Legalizacja Polska PL', 'legalizacja-polska.pl', 'https://legalizacja-polska.pl', 'html_list', 'legalization', '{"job_list":"article, .wp-block-post, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Karta Pobytu Info', 'karta-pobytu.info', 'https://karta-pobytu.info', 'html_list', 'residence_permit', '{"job_list":"article, .wp-block-post, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('VNZh Polsha', 'vnzh-polsha.com', 'https://vnzh-polsha.com', 'html_list', 'residence_permit', '{"job_list":"article, .wp-block-post, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Praca dla Obcokrajowcow', 'praca-dla-obcokrajowcow.pl', 'https://praca-dla-obcokrajowcow.pl', 'html_list', 'jobs', '{"job_list":"article, .wp-block-post, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Posvidka Polshcha', 'posvidka-polshcha.com', 'https://posvidka-polshcha.com', 'html_list', 'residence_permit', '{"job_list":"article, .wp-block-post, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Immigration Warsaw', 'immigration-warsaw.com', 'https://immigration-warsaw.com', 'html_list', 'immigration', '{"job_list":"article, .wp-block-post, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}'),
('Visa Polska', 'visa-polska.com', 'https://visa-polska.com', 'html_list', 'visa', '{"job_list":"article, .wp-block-post, .entry","title":"h2, h3, .entry-title","link":"a[href]","city":".city, .location","salary":".salary"}');
